name: NET CI/CD Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test-unit:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: "Your_password123"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --health-cmd " /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1' "
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Cache NuGet
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Esperar SQL Server
      run: sleep 20

    - name: Ejecutar pruebas unitarias
      env:
        ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=TestDB;User Id=sa;Password=Your_password123;TrustServerCertificate=True;"
      run: dotnet test --logger "trx" --results-directory TestResults

    - name: Subir artefactos
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Reporte-PruebasUnitarias
        path: TestResults/
        retention-days: 30
