name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validacion:
    runs-on: ubuntu-latest

    env:
      EnableWindowsTargeting: true

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Verificar versión de .NET
      run: dotnet --version

    - name: Mostrar información del entorno .NET
      run: dotnet --info

    - name: Listar SDKs instalados
      run: dotnet --list-sdks

    - name: Listar runtimes instalados
      run: dotnet --list-runtimes

    - name: Restaurar dependencias
      run: dotnet restore

    - name: Verificar cargas de trabajo (workloads)
      run: dotnet workload list

    - name: Compilar solución
      run: dotnet build --no-restore

    - name: Publicar aplicación (prueba)
      run: dotnet publish -c Release --no-build

    - name: Subir artefactos de compilación
      uses: actions/upload-artifact@v4
      with:
        name: salida-compilacion
        path: |
          **/bin/Release/**
